Hook the CreateDirectory*() functions
thelink2012/modloader pull request #122
Opened 2024-12-16 11:55 UTC by TheComputerGuy96

ZMenu still doesn't fully work with modloader though (the strings for the `Mod Configuration` menu are all empty which doesn't happen when using a normal ASI loader)

Maybe that issue could be worked around by delaying the loading of the modloader strings (but the mod should probably be fixed itself with some memory patches?)

2024-12-28 13:35 UTC, thelink2012 commented
Hey @TheComputerGuy96. Thanks for your contribution. I'll merge both this and #120 and publish a new release soon.

Just worried that this may cause some side-effect somewhere it shouldn't. But so far I've not thought of a edge case.

2025-02-21 18:52 UTC, SandeMC commented
@thelink2012 hey, any news on that release?

2025-03-07 11:42 UTC, thelink2012 commented
Hey @SandeMC, a bit busy here so I'll probably not be able to merge this before May.

2025-08-24 23:15 UTC, CanerKaraca23 commented
> Hey @SandeMC, a bit busy here so I'll probably not be able to merge this before May.

Hey, i hope you're not busy now.

2026-04-13 09:19 UTC, CookiePLMonster requested changes
`CreateDirectoryExA` and `CreateDirectoryExW` also need shims.

2026-04-25 23:02 UTC, thelink2012 commented
@TheComputerGuy96 thanks and sorry for the long day. 

Which mod is behaving badly because of the lack of CreateDirectory hooks? Can you provide more details? Is it ZMenu?

2026-04-26 02:58 UTC, TheComputerGuy96 commented
@thelink2012 ZMenu creates its own folder in the GTA San Andreas root folder (or maybe the folder relative to the .asi?) to store a speedrun configuration file (but due to the missing hook, the directory gets created in the wrong place and thus that config file likely can't be created due to the missing folder)

2026-04-26 16:48 UTC, merged

2026-04-26 16:48 UTC, thelink2012 commented
Thanks @TheComputerGuy96!